// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:113bf20e-27fb-4cb8-b5b3-4d3c70603da3',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_GBDllN7JY',
  aws_user_pools_web_client_id: 'saleor-cli',
  oauth: {
    domain: 'auth.staging.saleor.io',
    scope: ['email', 'openid', 'profile'],
    redirectSignIn: 'https://staging-cloud.saleor.io/',
    redirectSignOut: 'https://staging-cloud.saleor.io/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
};

export default awsmobile;
