// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_user_pools_web_client_id: 'saleor-cli',
  oauth: {
    domain: 'auth.staging.saleor.io',
    scope: ['email', 'openid', 'profile'],
  },
};

export default awsmobile;
