name: Execute nightly deployment tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0-6'

  repository_dispatch:
    types: [automation-tests-event]

jobs:
  run-functional-tests:
    if: ${{ github.event_name != 'repository_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Prepare saleor CLI
        run: pnpm build

      - name: Write config file
        id: write-config-file
        env:
          CLI_ACCESS_TOKEN: ${{ secrets.CLI_ACCESS_TOKEN }}
          CLI_GITHUB_TOKEN: ${{ secrets.CLI_GITHUB_TOKEN }}
          CLI_VERCEL_TOKEN: ${{ secrets.CLI_VERCEL_TOKEN }}
          TEST_COMMAND: 'node dist/saleor.js'
        run: echo '{"token":"${{ secrets.CLI_ACCESS_TOKEN }}","telemetry":"false", "github_token":"${{ secrets.CLI_GITHUB_TOKEN }}", "vercel_token":"${{ secrets.CLI_VERCEL_TOKEN }}"  }' > ~/.config/saleor.json

      - name: pre run
        env:
          SALEOR_CLI_ENV: staging
          RUN_FUNCTIONAL_TESTS: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node dist/saleor.js info
          node dist/saleor.js status

      - name: run tests
        env:
          SALEOR_CLI_ENV: staging
          RUN_FUNCTIONAL_TESTS: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'GA-saleor-cli'
          git config --global user.email 'GA-saleor-cli@users.noreply.github.com'
          pnpm vitest test/functional -t 'deploy' --no-threads